---
- name: test execution ssm on ansible 
  command: >
    aws ssm send-command --document-name {{ document }}  --parameters 'commands=['"mkdir /home/angel/ansible-test"']'  --targets {{ targets }}  --region {{  region }}
  register: cmd_result

- name: Check aws result
  debug:
    msg: "{{ cmd_result }}"