---
- name: test execution ssm on ansible 
  command: /usr/local/bin/aws ssm send-command --document-name {{ document }}  --parameters 'commands=['"mkdir /home/angel/ansible-test"']'  --targets {{ targets }}  --region {{  region }} --output text --no-verify-ssl
